### ISSUE TITLE
Source spans assume ASCII-only text and treat each byte as 1 character

### ISSUE THREAD

**Issue by Aloso** [zkat/miette#179] opened 2022-06-19 19:07 UTC
I use miette in [rulex](https://github.com/rulex-rs/rulex), where I discovered that the source span is at the wrong position if the same line contains non-ASCII characters

![rulex](https://user-images.githubusercontent.com/15658558/174495940-01876315-6f79-4b95-b583-05a50a885835.png)

## Things to take into account

1. Unicode code points sometimes span multiple bytes:
   ```rs
   assert_eq!("ä".len(), 2);                   // 2 bytes
   assert_eq!("ä".chars().count(), 1);         // 1 `char`
   ```

2. What we perceive as "characters" are actually _extended grapheme clusters_, which can consist of multiple code points:
   ```rs
   use unicode_segmentation::UnicodeSegmentation;

   assert_eq!("🤦🏼‍♂️".len(), 17);                   // 17 bytes
   assert_eq!("🤦🏼‍♂️".chars().count(), 5);          // 5 `char`s
   assert_eq!("🤦🏼‍♂️".graphemes(true).count(), 1);  // 1 extended grapheme cluster
   ```

3. A character _usually_ occupies exactly 1 column in a terminal, but not always. For example, emojis and many East Asian characters occupy 2 columns:
    ![echo](https://user-images.githubusercontent.com/15658558/174496525-c0248752-2410-4961-aa2f-de7a769950ec.png)

All of these can be addressed with the [unicode-width](https://docs.rs/unicode-width/latest/unicode_width/) crate.

**Comment by zkat** [comment] 2022-06-19 20:27
This is a duplicate of https://github.com/zkat/miette/issues/97. I'd love some help with this, since it's a pretty long-standing issue!

**Closed by zkat** 2022-06-19 20:27 UTC
