### ISSUE TITLE
Implement `WrapErr` for `Option`

### ISSUE THREAD

**Issue by LordMZTE** [zkat/miette#84] opened 2021-10-05 22:13 UTC
I've noticed, that unlike anyhow's `Context` trait, miette's `WrapErr` trait doesn't seem to be implemented for `Option`. Because of this, I sometimes have to do something like this, whenever I want to get a miette error when an option type is none:
```rust
some_option.ok_or_else(|| miette!("Option was none!"))?;
```
But I think it should be possible to implement `WrapErr` for Option, in order to allow something like this:
```rust
some_option.wrap_err("Option was none!")?;
```
That would make my code a lot cleaner!

**Comment by zkat** [comment] 2022-01-08 01:54
Closing this since it's as intended :)

**Closed by zkat** 2022-01-08 01:54 UTC
Labels: enhancement
